name: Bug Report
description: Create a bug report, so we can improve this repository
title: "bug: "
labels:
    - bug
body:
    - type: markdown
      attributes:
          value: |
              Please make sure to search through the open/closed issues before submitting this issue,
              as someone may have already made a similar issue previously!

              As we are are all volunteers on this repo, please make sure to take the time to correctly fill this
              issue form out so we can best deal with your issue.

              Thank you for filing in an issue, we appreciate that you have taken the time to do this. ❤️
    - type: "textarea"
      id: "description"
      attributes:
          label: "Description:"
          description: "Provide a brief description of the bug/issue."
      validations:
          required: true
    - type: "textarea"
      id: "expectation"
      attributes:
          label: "Expectation:"
          description: "What did you expect to happen?"
      validations:
          required: true
    - type: "textarea"
      id: "result"
      attributes:
          label: "Result:"
          description: "What was the actual result?"
      validations:
          required: true
    - type: "textarea"
      id: "reproduce"
      attributes:
          label: "Steps to reproduce:"
          description: "What are the steps to reproduce this issue?"
      validations:
          required: true
    - type: "textarea"
      id: "solution"
      attributes:
          label: "Possible Solution:"
          description: |
              Please provide a possible solution if you have one. This will speed up the development of the fix for
              this issue.
      validations:
          required: false
    - type: "textarea"
      id: "evidence"
      attributes:
          label: "Evidence:"
          description: |
              Provide any available evidence that may help us fix this bug/issue. This evidence can be a screenshot
              link, error message, a link to a minimal reproducible example, etc.
      validations:
          required: true
    - type: "textarea"
      id: "comments"
      attributes:
          label: "Additional Comments:"
          description: |
              Provide any additional information you think the team should know about this issue.
      validations:
          required: true
