blank_issues_enabled: false
contact_links:
    - name: Ask a Question
      url: https://github.com/skyebreach/breached-turbo/discussions
      about: Ask your questions (and answer others) about this project
